BEGIN;

DROP TABLE IF EXISTS user_posts;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS statuses;
DROP TABLE IF EXISTS genders;

COMMIT;